apiVersion: 1

datasources:
  - name: Adaptive Testing PostgreSQL
    uid: adaptive-postgres
    type: postgres
    access: proxy
    url: pgvector:5432
    user: $POSTGRES_USER
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      database: $POSTGRES_DB
      sslmode: disable
      postgresVersion: 1700
      timescaledb: false
    isDefault: true
    editable: false
